blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/djdarcy/reddit-slack/discussions
    about: Ask questions or discuss ideas that don't require a specific issue
  - name: Documentation
    url: https://github.com/djdarcy/reddit-slack/tree/main/docs
    about: Check our documentation for help with setup and usage
